name = "Powerful"
uuid = "542e4350-023d-42c7-b19f-8cb561780c9e"
authors = ["Hantao Cui <cuihantao@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
